//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportCompanion.Assets {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SupportCompanion.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DeviceInfoHostName {
            get {
                return ResourceManager.GetString("DeviceInfoHostName", resourceCulture);
            }
        }
        
        public static string DeviceInfoSerialNumber {
            get {
                return ResourceManager.GetString("DeviceInfoSerialNumber", resourceCulture);
            }
        }
        
        public static string DeviceInfoModel {
            get {
                return ResourceManager.GetString("DeviceInfoModel", resourceCulture);
            }
        }
        
        public static string DeviceInfoProcessor {
            get {
                return ResourceManager.GetString("DeviceInfoProcessor", resourceCulture);
            }
        }
        
        public static string DeviceInfoMemory {
            get {
                return ResourceManager.GetString("DeviceInfoMemory", resourceCulture);
            }
        }
        
        public static string DeviceInfoOSVersion {
            get {
                return ResourceManager.GetString("DeviceInfoOSVersion", resourceCulture);
            }
        }
        
        public static string DeviceInfoOSBuild {
            get {
                return ResourceManager.GetString("DeviceInfoOSBuild", resourceCulture);
            }
        }
        
        public static string DeviceInfoIP {
            get {
                return ResourceManager.GetString("DeviceInfoIP", resourceCulture);
            }
        }
        
        public static string DeviceInfoLastReboot {
            get {
                return ResourceManager.GetString("DeviceInfoLastReboot", resourceCulture);
            }
        }
        
        public static string DeviceInfoLastRebootToolTip {
            get {
                return ResourceManager.GetString("DeviceInfoLastRebootToolTip", resourceCulture);
            }
        }
        
        public static string DeviceInfo {
            get {
                return ResourceManager.GetString("DeviceInfo", resourceCulture);
            }
        }
        
        public static string DeviceManagement {
            get {
                return ResourceManager.GetString("DeviceManagement", resourceCulture);
            }
        }
        
        public static string DeviceManagementEnrolled {
            get {
                return ResourceManager.GetString("DeviceManagementEnrolled", resourceCulture);
            }
        }
        
        public static string DeviceManagementEnrollmentDate {
            get {
                return ResourceManager.GetString("DeviceManagementEnrollmentDate", resourceCulture);
            }
        }
        
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        public static string StorageName {
            get {
                return ResourceManager.GetString("StorageName", resourceCulture);
            }
        }
        
        public static string StorageUsage {
            get {
                return ResourceManager.GetString("StorageUsage", resourceCulture);
            }
        }
        
        public static string EvergreenCatalogs {
            get {
                return ResourceManager.GetString("EvergreenCatalogs", resourceCulture);
            }
        }
        
        public static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        public static string BatteryHealth {
            get {
                return ResourceManager.GetString("BatteryHealth", resourceCulture);
            }
        }
        
        public static string BatteryCycleCount {
            get {
                return ResourceManager.GetString("BatteryCycleCount", resourceCulture);
            }
        }
        
        public static string ApplicationInstallProgress {
            get {
                return ResourceManager.GetString("ApplicationInstallProgress", resourceCulture);
            }
        }
        
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        public static string ActionsChangePassword {
            get {
                return ResourceManager.GetString("ActionsChangePassword", resourceCulture);
            }
        }
        
        public static string ActionsReboot {
            get {
                return ResourceManager.GetString("ActionsReboot", resourceCulture);
            }
        }
        
        public static string ActionsRestartIntuneAgent {
            get {
                return ResourceManager.GetString("ActionsRestartIntuneAgent", resourceCulture);
            }
        }
        
        public static string ActionsGetSupport {
            get {
                return ResourceManager.GetString("ActionsGetSupport", resourceCulture);
            }
        }
        
        public static string ActionsGatherLogs {
            get {
                return ResourceManager.GetString("ActionsGatherLogs", resourceCulture);
            }
        }

        public static string ActionsSupportInfo {
            get {
                return ResourceManager.GetString("ActionsSupportInfo", resourceCulture);
            }
        }
        
        public static string ActionsSoftwareUpdates {
            get {
                return ResourceManager.GetString("ActionsSoftwareUpdates", resourceCulture);
            }
        }
        
        public static string ActionsOpenMSC {
            get {
                return ResourceManager.GetString("ActionsOpenMSC", resourceCulture);
            }
        }
        
        public static string PendingUpdates {
            get {
                return ResourceManager.GetString("PendingUpdates", resourceCulture);
            }
        }
        
        public static string PendingUpdatesOpenMSC {
            get {
                return ResourceManager.GetString("PendingUpdatesOpenMSC", resourceCulture);
            }
        }
        
        public static string PendingUpdatesOpenCompanyPortal {
            get {
                return ResourceManager.GetString("PendingUpdatesOpenCompanyPortal", resourceCulture);
            }
        }
        
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        public static string MenuApplications {
            get {
                return ResourceManager.GetString("MenuApplications", resourceCulture);
            }
        }
        
        public static string MenuIdentity {
            get {
                return ResourceManager.GetString("MenuIdentity", resourceCulture);
            }
        }
        
        public static string InstalledApps {
            get {
                return ResourceManager.GetString("InstalledApps", resourceCulture);
            }
        }
        
        public static string InstalledAppsManage {
            get {
                return ResourceManager.GetString("InstalledAppsManage", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string UserInformation {
            get {
                return ResourceManager.GetString("UserInformation", resourceCulture);
            }
        }

        public static string UserInformationLogin
        {
            get
            {
                return ResourceManager.GetString("UserInformationLogin", resourceCulture); 
                
            }
        }
        
        public static string UserInformationUsername {
            get {
                return ResourceManager.GetString("UserInformationUsername", resourceCulture);
            }
        }
        
        public static string UserInformationHomeDirectory {
            get {
                return ResourceManager.GetString("UserInformationHomeDirectory", resourceCulture);
            }
        }
        
        public static string KerberosSSORealm {
            get {
                return ResourceManager.GetString("KerberosSSORealm", resourceCulture);
            }
        }
        
        public static string KerberosSSOADUsername {
            get {
                return ResourceManager.GetString("KerberosSSOADUsername", resourceCulture);
            }
        }
        
        public static string KerberosSSOLastLocalPasswordChange {
            get {
                return ResourceManager.GetString("KerberosSSOLastLocalPasswordChange", resourceCulture);
            }
        }
        
        public static string KerberosSSOLastADPasswordChange {
            get {
                return ResourceManager.GetString("KerberosSSOLastADPasswordChange", resourceCulture);
            }
        }
        
        public static string KerberosSSOADPasswordExpiry {
            get {
                return ResourceManager.GetString("KerberosSSOADPasswordExpiry", resourceCulture);
            }
        }
        
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        public static string PlatformSSOExtensionIdentifier {
            get {
                return ResourceManager.GetString("PlatformSSOExtensionIdentifier", resourceCulture);
            }
        }
        
        public static string PlatformSSOLoginFrequency {
            get {
                return ResourceManager.GetString("PlatformSSOLoginFrequency", resourceCulture);
            }
        }
        
        public static string PlatformSSOLoginType {
            get {
                return ResourceManager.GetString("PlatformSSOLoginType", resourceCulture);
            }
        }
        
        public static string PlatformSSONewUserAuthorizationMode {
            get {
                return ResourceManager.GetString("PlatformSSONewUserAuthorizationMode", resourceCulture);
            }
        }
        
        public static string PlatformSSOSDKVersion {
            get {
                return ResourceManager.GetString("PlatformSSOSDKVersion", resourceCulture);
            }
        }
        
        public static string PlatformSSOSharedDeviceKeys {
            get {
                return ResourceManager.GetString("PlatformSSOSharedDeviceKeys", resourceCulture);
            }
        }
        
        public static string PlatformSSOUserAuthorizationMode {
            get {
                return ResourceManager.GetString("PlatformSSOUserAuthorizationMode", resourceCulture);
            }
        }
        
        public static string PlatformSSORegistrationCompleted {
            get {
                return ResourceManager.GetString("PlatformSSORegistrationCompleted", resourceCulture);
            }
        }
        
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        public static string NativeMenuSystemUpdates {
            get {
                return ResourceManager.GetString("NativeMenuSystemUpdates", resourceCulture);
            }
        }
        
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string SupportDialogEmail {
            get {
                return ResourceManager.GetString("SupportDialogEmail", resourceCulture);
            }
        }
        
        public static string SupportDialogPhone {
            get {
                return ResourceManager.GetString("SupportDialogPhone", resourceCulture);
            }
        }
    }
}
